### ISSUE TITLE
PhaseMixins can be subtypes of RoleMixins?

### ISSUE THREAD

**Issue by andredemori** [OntoUML/ontouml-vp-plugin#113]
This question arose because when modeling in OntoUML, there is no syntactic error referring to placing a PhaseMixin as a subtype of a RoleMixin. However, the page 

https://ontouml.readthedocs.io/en/latest/classes/nonsortals/phasemixin/index.html 

does not state that PhaseMixins can be subtypes of RoleMixins. I think the web page should be updated.

The follow article uses this example in one of your models: _A Reference Ontology of Money and Virtual Currencies_

I also noticed that Category can also be a supertype of RoleMixins and PhaseMixins and that it doesn't appear on the webpage

**Comment by claudenirmf** [comment]
Indeed these are issues in the documentation, thanks for noticing. As of now we have not identified constraints ruling out specializations between phases and roles.

I have created an issue on the [documentation repository](https://github.com/OntoUML/OntoUML/issues/29#issue-1005526456) to keep track of this.

**Comment by claudenirmf** [comment]
As this issue does not refer to the plugin itself, I'll be closing it now.
