### ISSUE TITLE
Behavior when evaluating the absence of associations' stereotypes

### ISSUE THREAD

**Issue by pedropaulofb** [OntoUML/ontouml-vp-plugin#124]
Shouldn't the absence of OntoUML stereotypes for **associations** be reported as a problem when clicking on the Check Model button? Maybe at least a warning should be given so that the modeler can be aware of the situation.

**Comment by claudenirmf** [comment]
The verification of associations is already on track to be implemented on the backend. For this reason, and due to the fact this cannot be solved by the plugin itself, I will be closing your issue.
