### ISSUE TITLE
Where can I find documentation about the OntoUML stereotypes?

### ISSUE THREAD

**Issue by JoranL** [OntoUML/ontouml-vp-plugin#134]
The stereotypes that appear when I right-click does not completely correspond to the documentation in [https://ontouml.readthedocs.io/en/.](https://ontouml.readthedocs.io/en/) For example, “triggers”.

Thank you for your work!

**Comment by pedropaulofb** [comment]
Hi @JoranL, thank you for your contribution. We are aware that the OntoUML specification presented in https://ontouml.readthedocs.io/en/latest/ is outdated when compared to the VP plugin.

Please consider the following references as the most precise ones for the VP plugin:

For classes' stereotypes:

- [Types and taxonomic structures in conceptual modeling: A novel ontological theory and engineering support](https://www.sciencedirect.com/science/article/pii/S0169023X21000185)
- [Endurant types in ontology-driven conceptual modeling: Towards OntoUML 2.0](https://link.springer.com/chapter/10.1007/978-3-030-00847-5_12)

For associations' stereotypes:

- [Relations in ontology-driven conceptual modeling](https://link.springer.com/chapter/10.1007/978-3-030-33223-5_4)

**Comment by JoranL** [comment]
Many thanks @pedropaulofb, I will read those papers and definitely consider using the repository.
