### ISSUE TITLE
Run syntax verification on currently open diagram

### ISSUE THREAD

**Issue by victorviola** [OntoUML/ontouml-vp-plugin#21]
Syntax verification limited to diagram elements (on-demand).

**Comment by tgoprince** [comment]
This feature consists in:

1. Adding a button to the plugin toolbar called "Diagram Verification".
2. Clicking this button should trigger the normal syntax verification feature, but show on the Log Panel only the errors that are related to the elements shown in the current diagram.

Note that the verification should run on the whole model. The difference in this feature is that the received errors should be filtered.
