### ISSUE TITLE
UI for the ontouml2gufo transformation

### ISSUE THREAD

**Issue by victorviola** [OntoUML/ontouml-vp-plugin#22]
In the plugin, the transformation must be requested through a button.

The button must open a window requesting the baseIRI, the desired syntax (format), and if entities should be identified by name or by id (uriFormatBy).

baseIRI must be a text field.

format must be a drop down with options: `N-Triples`, `N-Quads`, and `Turtle`.

uriFormatBy must be a drop down with options `name` and `id`.

The information must be saved in the configurations for future transformations.

Upon a successful response, a window must appear requesting for the path to save the transformed file.

The path must be saved for future transformations.

Upon an unsuccessful request, a dialog must appear informing the user that a problem occurred.

**Comment by tgoprince** [comment]
This is the structure of options object that the ontouml2gufo service accepts:

```typescript
{
  baseIRI: string;
  createInverses?: boolean;
  createObjectProperty?: boolean;
  customElementMapping?: {
    [key: string]: {
      label?: {
        [key: string]: string;
      };
      uri: string;
    };
  };
  customPackageMapping?: {
    [key: string]: {
      prefix: string;
      uri: string;
    };
  };
  format?: string;
  preAnalysis?: boolean;
  prefixPackages?: boolean;
  uriFormatBy?: 'name' | 'id';
}
```
