### ISSUE TITLE
Open a diagram containing the element that is the source of the error 

### ISSUE THREAD

**Issue by victorviola** [OntoUML/ontouml-vp-plugin#24]
The plugin should highlight model elements that are causing an error

**Comment by tgoprince** [comment]
This feature consists in allowing the user to request the tool to open a diagram in which the element that is the source of the error appears.

To implement this feature, we need to redesign the Error Log Panel we are currently using.

**Comment by tgoprince** [comment]
You can use the old plugin for inspiration on how to create a more complex log panel: https://github.com/mvp-sales/ontouml-vp-plugin
