### ISSUE TITLE
Add an additional "apply stereotype" menu

### ISSUE THREAD

**Issue by tgoprince** [OntoUML/ontouml-vp-plugin#38]
The current menu to apply stereotypes helps users by disabling stereotypes that are not applicable in specific situations. For instance, if the class `Man` specializes the class `<<kind>> Person`, and the user clicks on `Man`, the tool only allows the following stereotypes to be applied: `<<subkind>>`, `<<role>>`, `<<phase>>`, and `<<historicalRole>>`.

In some situations, however, disabling the stereotypes actually blocks the user from doing what she needs to do, such as changing the nature of a class completely (e.g. from kind to event). That may happen because of a previous wrong decision the stereotype was added accident.

To accommodate these situations, I propose we add an additional "Apply stereotype" menu that does not disable any stereotype. Then, the original one could be renamed to "Recommended stereotypes". 

What do you think @victorviola and @claudenirmf ?

**Comment by claudenirmf** [comment]
I agree that it is an important feature, but I believe the solution has its own drawbacks. I would prefer to create an "OntoUML Open Specifications" window which allows such supports such edits instead, but probably this is not a good short-term option.

I will experiment if the plugin later to check what other options we might have.

**Comment by tgoprince** [comment]
Could you elaborate on drawbacks do you foresee?

Also, I did not understand what you mean by "OntoUML Open Specifications" window and why it is not a good option...

**Comment by claudenirmf** [comment]
The drawback with the context menu, if I got it right, is to have multiple "redundant" menus. I am not sure how they would be placed, but maybe just the organization of these menus could be good enough, like in the example below:

<img width="845" alt="Screen Shot 2020-03-26 at 02 50 53" src="https://user-images.githubusercontent.com/12445213/77602053-bb3f4d00-6f0c-11ea-8f3d-d2a6a2863b36.png">

I am cautious as well about introducing context menus as many of them may slow down the modeling process.

Additionally, when I was talking about a "specifications window" I was referring to the following, but a version specific for OntoUML properties:

<img width="707" alt="Screen Shot 2020-03-26 at 02 51 08" src="https://user-images.githubusercontent.com/12445213/77602125-e7f36480-6f0c-11ea-8659-768f6a5dd72d.png">
