### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by mrverdonck** [OntoUML/ontouml-vp-plugin#47]
When trying to create a Category or a Role, I consistently get a java.lang.NullPointerException when I want to save the project (which is no longer possible then). Not sure if this is purely related to the ontouml-vp-plugin.

![Screenshot 2020-04-29 at 10 53 22](https://user-images.githubusercontent.com/9342234/80578036-2f877780-8a08-11ea-836a-e8d1a56dafca.png)
![Screenshot 2020-04-29 at 10 55 30](https://user-images.githubusercontent.com/9342234/80578046-31513b00-8a08-11ea-9b40-141a33fed855.png)

**Comment by victorviola** [comment]
Hi @mrverdonck,
I tried to replicate your scenario in a recent version of the plugin and I wasn't able to find this null pointer exception behavior. Perhaps you are using an old version of the plugin.

Could you please upgrade your plugin for this newer version? I just added a new release (0.2.0) [here](https://github.com/OntoUML/ontouml-vp-plugin/releases/tag/0.2.0).

If the plugin is still showing any strange behavior, please inform.

Cheers.
