### ISSUE TITLE
Default color for situations

### ISSUE THREAD

**Issue by tgoprince** [OntoUML/ontouml-vp-plugin#57]
**Plugin version:** 0.3.0

The default color of a class stereotyped as <<situation>> is a light yellow, the same one used for classes stereotyped as <<event>>.

<img width="647" alt="situation-yellow" src="https://user-images.githubusercontent.com/2519935/89270102-275c5b00-d63b-11ea-9a54-6cdddb7d8433.png">

I propose we pick a different color for situations, so we can properly distinguish them from events.
Maybe a light orange?

<img width="648" alt="situation-orange" src="https://user-images.githubusercontent.com/2519935/89270090-2297a700-d63b-11ea-9c26-22bc0691c1bc.png">

**Comment by claudenirmf** [comment]
The choice for yellow was deliberate and a discussion on the current color scheme was expected, I would only like us to have a couple of points in mind.

* situations may deserve their own color as they indicate a totally different ontological nature
* the color of situations should harmonize with the color of events as these two are expected to appear in most diagrams together
* last, but not least, the color scheme should have in mind color filters (e.g., b/w for printing or colorblind-friendly color schemes)

Even though using orange nicely fits the two first points, it fails the third. Magenta would be an easy to differentiate option, but it would not harmonize. That being said, I suggest that we use orange and add custom color schemes   (see #52)  and diagram color legends (see #51) for the next release.
