### ISSUE TITLE
Does OntoUML support non-sortal moments (i.e., categories, mixins, role mixins, and phase mixins)?

### ISSUE THREAD

**Issue by brunogcarneiro** [OntoUML/ontouml-vp-plugin#83]
Hello,

In my model, I have a class <<mode>> that specializes other class <<category>> but the "model check" functionality don't complains about that.

This make sense? Shouldn't the validation acknowledge this error?

Instances of a <<mode>> class are moments while instances of a <<category>> class are substantials. Moment and Substantial are disjoint classes.

**Comment by claudenirmf** [comment]
Actually, no, the current version of OntoUML does support non-sortal classes of both moments and substantial, even combinations of both (see [here](https://www.researchgate.net/profile/Giancarlo_Guizzardi2/publication/325995419_Endurant_Types_in_Ontology-Driven_Conceptual_Modeling_Towards_OntoUML_20/links/5b329bc10f7e9b0df5ccb666/Endurant-Types-in-Ontology-Driven-Conceptual-Modeling-Towards-OntoUML-20.pdf)).

However, you must set the `restrictedTo` meta-property properly. A class can only specialize another class that includes the same values of `restrictedTo`.
For example, the `restrictedTo` of the `«mixin»` `Insured Item` is `functional-complex`, `collective`, and `relator`. Thus, you may specialize the class `Insured Item` into `«relator»` `Employment Contract` and `«kind»` `Car` without a problem as it includes both `functional-complex` and `relator`.

Whenever possible, please share with us a screenshot of the piece you have questions about. That way it easier for us to provide support.

Also, share with us the values of `restrictedTo` of these classes you mentioned. I would like to check that.
